package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"html/template"
	"io"
	"os"
	"strings"

	"github.com/wneessen/go-mail"
)

type NewsItem struct {
	Title     string `json:"title"`
	Summary   string `json:"summary"`
	SourceURL string `json:"source_url"`
	Category  string `json:"category"`
}

type NewsDigest struct {
	Items      []NewsItem `json:"items"`
	SearchDate string     `json:"search_date"`
	ItemCount  int        `json:"item_count"`
}

var htmlTmpl = template.Must(template.New("email").Parse(`<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body style="margin:0;padding:0;background:#f4f4f4;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">
<table width="100%" cellpadding="0" cellspacing="0" style="background:#f4f4f4;padding:20px 0;">
<tr><td align="center">
<table width="600" cellpadding="0" cellspacing="0" style="background:#fff;border-radius:8px;overflow:hidden;">
  <tr><td style="background:#1a1a2e;padding:24px 32px;">
    <h1 style="margin:0;color:#fff;font-size:22px;">AI News Digest</h1>
    <p style="margin:4px 0 0;color:#a0a0b0;font-size:13px;">{{.SearchDate}}</p>
  </td></tr>
  <tr><td style="padding:24px 32px;">
    {{range .Items}}
    <table width="100%" cellpadding="0" cellspacing="0" style="margin-bottom:20px;">
      <tr><td>
        <span style="display:inline-block;background:#e8eaf6;color:#3949ab;font-size:11px;font-weight:600;padding:2px 8px;border-radius:4px;margin-bottom:6px;">{{.Category}}</span>
        <h2 style="margin:6px 0 4px;font-size:16px;"><a href="{{.SourceURL}}" style="color:#1a1a2e;text-decoration:none;">{{.Title}}</a></h2>
        <p style="margin:0;color:#555;font-size:14px;line-height:1.5;">{{.Summary}}</p>
      </td></tr>
    </table>
    {{end}}
  </td></tr>
  <tr><td style="padding:16px 32px;background:#f8f8f8;text-align:center;">
    <p style="margin:0;color:#999;font-size:12px;">Generated by AI News Digest</p>
  </td></tr>
</table>
</td></tr>
</table>
</body>
</html>`))

var plainTmpl = template.Must(template.New("plain").Parse(`AI News Digest — {{.SearchDate}}
========================================
{{range .Items}}
[{{.Category}}] {{.Title}}
{{.Summary}}
Link: {{.SourceURL}}
{{end}}
---
Generated by AI News Digest
`))

func main() {
	data, err := io.ReadAll(os.Stdin)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error reading stdin: %v\n", err)
		os.Exit(1)
	}

	var digest NewsDigest
	if err := json.Unmarshal(data, &digest); err != nil {
		fmt.Fprintf(os.Stderr, "error parsing JSON: %v\n", err)
		os.Exit(1)
	}

	var htmlBuf strings.Builder
	if err := htmlTmpl.Execute(&htmlBuf, digest); err != nil {
		fmt.Fprintf(os.Stderr, "error rendering HTML: %v\n", err)
		os.Exit(1)
	}

	var plainBuf strings.Builder
	if err := plainTmpl.Execute(&plainBuf, digest); err != nil {
		fmt.Fprintf(os.Stderr, "error rendering plain text: %v\n", err)
		os.Exit(1)
	}

	host := flag.String("smtp-host", "", "SMTP server hostname")
	port := flag.Int("smtp-port", 587, "SMTP server port")
	user := flag.String("smtp-user", "", "SMTP username")
	password := flag.String("smtp-password", "", "SMTP password")
	from := flag.String("from", "", "Sender email address")
	to := flag.String("to", "", "Recipient email address")
	flag.Parse()

	if *host == "" || *user == "" || *password == "" || *from == "" || *to == "" {
		fmt.Fprintln(os.Stderr, "error: missing required flags (--smtp-host, --smtp-user, --smtp-password, --from, --to)")
		flag.Usage()
		os.Exit(1)
	}

	m := mail.NewMsg()
	if err := m.From(*from); err != nil {
		fmt.Fprintf(os.Stderr, "error setting from: %v\n", err)
		os.Exit(1)
	}
	if err := m.To(*to); err != nil {
		fmt.Fprintf(os.Stderr, "error setting to: %v\n", err)
		os.Exit(1)
	}
	m.Subject(fmt.Sprintf("AI News Digest — %s", digest.SearchDate))
	m.SetBodyString(mail.TypeTextPlain, plainBuf.String())
	m.AddAlternativeString(mail.TypeTextHTML, htmlBuf.String())

	c, err := mail.NewClient(*host,
		mail.WithPort(*port),
		mail.WithSMTPAuth(mail.SMTPAuthPlain),
		mail.WithUsername(*user),
		mail.WithPassword(*password),
		mail.WithTLSPortPolicy(mail.TLSMandatory),
	)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error creating mail client: %v\n", err)
		os.Exit(1)
	}

	if err := c.DialAndSend(m); err != nil {
		fmt.Fprintf(os.Stderr, "error sending email: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Email sent to %s (%d items)\n", *to, digest.ItemCount)
}
